Worky/Controllers/FilesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Worky.Data.Project;
using Worky.Models.Project;
using Worky.Project;

namespace Worky.Controllers
{
    public class FilesController : Controller
    {
        Data.Project.IdFilesDb filesDB;
        Data.Project.IProjectDb prj;
        public FilesController(ProjectDbContext context)
        {
            filesDB = context;
            prj= context;
        }
        [HttpGet]
        public IActionResult AddTaskFile(int TaskId)
        {
            Models.AddTaskFileModel model = new Models.AddTaskFileModel()
            {
                TaskId = TaskId
            };
            return View(model);
        }
        [HttpPost]
        public IActionResult AddTaskFile(IFormFile uploadedFile, int TaskId)
        {
            //   int TaskId = TaskId;


            
            if (uploadedFile.Length > 0)
            {

                
                    DFile file = new DFile(uploadedFile);
                    filesDB.AddFile(file);
                    TaskFile ts =new TaskFile();
                    ts.TaskId = TaskId;
                    ts.FileId = file.Id;
                    ts.Name = file.Name;
                    prj.AddTaskFile(ts);

            }
           
            return RedirectToAction("Edit","Task", new { TaskId = TaskId });
            



        }
        [HttpPost]
        public IActionResult DownloadTaskFile(int TaskFileId)
        {
            
            
            TaskFile f = prj.GetTaskFileById(TaskFileId);
            DFile dFile = filesDB.GetById(f.FileId);
            return DownloadFile(dFile.Id);
        }
        
        public IActionResult  DownloadFile(int id)
        {
            
            DFile file = filesDB.GetById(id);

           
            return File(file.Bytes, file.ContentType);
        }
        [HttpPost]
        public void RemoveTaskFile(int TaskFileId)
        {
          
            TaskFile f = prj.GetTaskFileById(TaskFileId);
            DFile dFile = filesDB.GetById(f.FileId);
            prj.RemoveTaskFile(f);
            filesDB.Remove(dFile);

        }


    }
}

Worky/Controllers/TaskController.cs
using Microsoft.AspNetCore.Mvc;
using Worky.Models.Project;
using Worky.Project;
using Worky.Project.Task;
using Worky.Users;
using Worky.Data.Project;
using Worky.Data.Tags;
using Worky.Project.Tags;
using Worky.Models.TaskTags;
using Worky.Services;

namespace Worky.Controllers
{
    public class TaskController : Controller
    {
        IProjectDb projectDb;
        IUsersCollection usersDb;
        ITagsDb tagsDb;
        ITaskCommentsDb taskCommentsDb;
        IdFilesDb filesDb;
        public TaskController(ProjectDbContext db,IUsersCollection _users, ITagsDb _tags)
        {
            projectDb = db;
            usersDb = _users;
            tagsDb = _tags;
            taskCommentsDb = db;
        }
        [HttpGet]
        public IActionResult Edit(int TaskId)
        {
            
            Worky.Project.Task.Task task= projectDb.GetTaskById(TaskId);

           
            
            Users.User user = usersDb.GetUser(User.Identity.Name);

            EditTaskModel model = CreateEditModel(task);
            
             
            model.BackLink = $"~/Tasks/ProjectTasks?ProjectId={task.ProjectId}";
            return View(model);
        }
        private EditTaskModel CreateEditModel(Worky.Project.Task.Task task)
        {
           
            Models.Project.EditTaskModel model = new Models.Project.EditTaskModel(task);


            model.Owner = usersDb.GetUser(task.AutorId);
            model.TaskStatuses = projectDb.GetTaskStatuses(task.ProjectId);




           
                 List<CommentModel> comments = GetTaskCommentsForTask(task.Id);
                 model.SetCommentsModel(comments);
           

          

            
                task.TaskFiles = projectDb.GetTaskFiles(task.Id);
                  
            

            
                TagType[] ProjectTags = tagsDb.GetTagTypesForProject(task.ProjectId);
                TagTaskInstance[] tagTaskInstances = tagsDb.GetTagTaskInstancesForTask(task.Id);

                foreach (TagTaskInstance t in tagTaskInstances)
                {
                    TagType type = tagsDb.GetTagTypeByid(t.TagTypeId);
                    TagTaskInstanceModel tagmodel = new TagTaskInstanceModel()
                    {
                        Id = t.Id,
                        Name = type.Name,
                        TagTypeId = type.Id
                    };

                    model.AddTag(tagmodel);
                }
            


           


           

            return model;
        }
        private List<CommentModel> GetTaskCommentsForTask(int TaskId)
        {
            List<CommentModel> modesl = new List<CommentModel>();
            List<TaskComment> taskComments = projectDb.GetTaskCommentsByTaskId(TaskId);
            foreach(TaskComment c in taskComments)
            {
                CommentModel model = new CommentModel(c);
                model.User=usersDb.GetUser(c.UserId);
                modesl.Add(model);

            }




            return modesl;
            
        }
        [HttpPost]
        public IActionResult Edit(Models.Project.EditTaskModel model)
        {
           
            Worky.Project.Task.Task task = projectDb.GetTaskById(model.TaskId);
            task.SetData(model);
            projectDb.Update(task);

            return RedirectToAction("Edit", new { TaskId = task.Id });
        }
        public IActionResult AddNewComment(CommentAddModel model)
        {

            CurrentUser user = new CurrentUser(User);

            TaskComment com = new TaskComment();
            com.TaskId = model.TaskId;
            com.Comment = model.Content;
            com.UserId = user.Id;
            com.DateTime = DateTime.Now;
            projectDb.AddCommentToTask(com);

            return RedirectToAction("Edit", new { TaskId = model.TaskId });
        }
        public IActionResult AddNewTask(int TaskStatusId)
        {
           
             
            Worky.Project.Task.TaskStatus st = projectDb.GetTaskStatusById(TaskStatusId);


            Worky.Project.Task.Task t = new Worky.Project.Task.Task();
            t.CreationTime = DateTime.Now;
            t.TaskStatusId = TaskStatusId;
            t.ProjectId = st.ProjectId;
            
            projectDb.AddTask(t);
            return RedirectToAction("ProjectTasks","Tasks", new { ProjectId = st.ProjectId });
        }
        public IActionResult DeleteTask(int TaskId)
        {
            TaskServices taskServices = new TaskServices(projectDb, taskCommentsDb, filesDb);
            taskServices.RemoveTask(TaskId);

            Worky.Project.Task.Task task = projectDb.GetTaskById(TaskId);
            projectDb.DeleteTask(task);
            
          

            return RedirectToAction("ProjectTasks", "Tasks", new { ProjectId = task.ProjectId });

        }
       
       
        
        


    }
}

Worky/Controllers/TasksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Worky.Data;
using Worky.Data.Project;
using Worky.Models.Project;
using Worky.Users;

namespace Worky.Controllers
{
    [Authorize]
    public class TasksController : Controller
    {
        IProjectDb projects;
        IIviteCollection invitesToProject;
        IUsersCollection users;
        public TasksController(ProjectDbContext db, IUsersCollection _users)
        {
            projects = db;
            invitesToProject = db;
            users = _users;
        }
        public IActionResult EditColumnTask(int ProjectId)
        {
             
            List<Worky.Project.Task.TaskStatus> taskStatuses = projects.GetTaskStatuses(ProjectId);
            Models.Project.ShowAllTaskStatusModel model = new Models.Project.ShowAllTaskStatusModel();
            model.ProjectId = ProjectId;
            model.TaskStatuses = taskStatuses;
            return View(model);
        }
        public IActionResult DeleteTaskStatus(int id)
        {
            
            Worky.Project.Task.TaskStatus ts = projects.GetTaskStatusById(id);
            projects.RemoveTaskStatus(ts);

            return RedirectToAction("EditColumnTask", new { ProjectId = ts.ProjectId });
        }
        public IActionResult AddNewTaskStatusId(int ProjectId)
        {
             
            Worky.Project.Task.TaskStatus st = new Project.Task.TaskStatus();
            st.ProjectId = ProjectId;
            st.Name = "New Column";

            projects.AddTaskStatus(st);

            return RedirectToAction("EditColumnTask", new { ProjectId = ProjectId });
        }
        public IActionResult ProjectTasks(int ProjectId)
        {
            
            Worky.Users.User user = users.GetUser(User.Identity.Name);

            Project.Project project = projects.GetProject(ProjectId);
            if(project==null)
            {
               
                return RedirectToAction("NoAccess", "Msg");
            }
            Services.UserAcsessService accesService = new Services.UserAcsessService(invitesToProject, projects);
            
            if (accesService.IsUserAccsessToProject(user, project)== false)
            {
                return RedirectToAction("NoAccess", "Msg");
            }

            TasksSetModel model = new  TasksSetModel();
            model.ProjectId = ProjectId;
            List<Project.Task.Task> tasks = projects.GetTasksForProject(ProjectId);
            List<Worky.Project.Task.TaskStatus> taskStatuses = projects.GetTaskStatuses(project.Id);

            if(taskStatuses.Count==0)
            {
                Worky.Project.Task.TaskStatus.CreateDefultTaskSttusForProject(projects, ProjectId);
                taskStatuses = projects.GetTaskStatuses(project.Id);
            }

            SortTask(tasks, taskStatuses);
            //foreach(Project.Task.TaskStatus taskStatus in taskStatuses)
            //{
            //    taskStatus.Tasks.AddRange(tasks.Where(i => i.TaskStatusId == taskStatus.Id));
            //}
            
                model.Statuses = taskStatuses;
            
            

          


            return View(model);
        }
        private void SortTask(List<Project.Task.Task> tasks, List<Worky.Project.Task.TaskStatus> taskStatuses)
        {
            foreach(Project.Task.Task task in tasks)
            {
                Project.Task.TaskStatus st =  taskStatuses.Where(i => i.Id == task.TaskStatusId).FirstOrDefault();
                if(st==null)
                {
                    taskStatuses[0].Tasks.Add(task);
                }
                else
                {
                    st.Tasks.Add(task);
                }

            }
        }
        public IActionResult AddNewTask(int TaskStatusId)
        {
             
            Worky.Project.Task.TaskStatus st= projects.GetTaskStatusById(TaskStatusId);
            Project.Task.Task task = new Project.Task.Task();
            task.CreationTime = DateTime.Now;
            task.TaskStatusId = st.Id;
            task.ProjectId = st.ProjectId;
            projects.AddTask(task);
            

           
            return RedirectToAction("ProjectTasks", new { ProjectId = st.ProjectId });
        }
        
        [HttpGet]
        public IActionResult EditTaskStatus(int id)
        {
             
            Worky.Project.Task.TaskStatus ts= projects.GetTaskStatusById(id);

            return View(ts);
        }
        [HttpPost]
        public IActionResult EditTaskStatus(Worky.Project.Task.TaskStatus model)
        {
            
            projects.Update(model);

            return RedirectToAction("EditColumnTask", new { ProjectId = model.ProjectId });
        }

    }
}

Worky/Views/Task/CommentAddView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using Worky.Models.Project;

@model CommentAddModel 

<form  action="AddNewComment">
        <input asp-for="@Model.TaskId" hidden />
         
        <div style="display:flex; flex-direction:column;">
        <input asp-for="@Model.Content" class="form-control" style="height:60px;" placeholder="Ваш комментарий" />
        <input style: type="submit" value="Отправить" class="Dbtn"/>
        </div>
      
</form>
@{
}

Worky/Views/Task/CommentView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using Worky.Models.Project;
@model CommentModel 
    <div class="list-group-item list-group-item-action py-3 lh-tight"  style="display:flex; flex-direction:column">
            <h5>@Model.GetuserName()</h5>
            @Model.Comment
            <br>
            <hr>
            <a>@Model.DateTime</a>
    </div>
@{
}

Worky/Views/Task/CommentsView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@using Worky.Models.Project;
@model List<CommentModel> 

@{
}


<div>
     <div style="overflow:auto;max-height:300px" >
    @foreach(CommentModel c in Model)
    {
        @Html.Partial("CommentView",c);
         
    }
     </div>
</div>

Worky/Views/Task/Edit.cshtml
@using Worky.Models.Project;
@using Worky.Models.TaskTags;
@model Worky.Models.Project.EditTaskModel

@{
    ViewData["Title"] = "Edit";
}
@{
    Layout = "_Layout";
}
<head>
    <style>
        .blockPadding{
            padding-top:5em;
            
        }
    </style>
     <link rel="stylesheet" href="~/css/EditCard.css" asp-append-version="true" />
      <link rel="stylesheet" href="~/css~/css/site.css" asp-append-version="true" />
      <script>
          function RemoveFile(id)
          {
              var ElmId='TaskFile-'+id;
                
              var elm=document.getElementById(ElmId);
             

            var xhr = new XMLHttpRequest();

            

            xhr.open("POST", '/Files/RemoveTaskFile?TaskFileId='+id, true);

        

            xhr.send();

              elm.remove();

             
             
          }
      </script>

</head>

<div>
    <div style="display:grid; grid-template-columns: 1fr 100px;">
        <h2>Редактирование</h2>
       
    </div>
    <hr />
    <div style="display:grid; grid-template-columns:1fr 75px">
        <div>
              <a href="/Tasks/ProjectTasks?ProjectId=@Model.ProjectId" class="Dbtn">К Задачам</a>
        </div>
     
         <div>
              <a href="/Task/DeleteTask?TaskId=@Model.TaskId" class="Dbtn">Удалить</a>
         </div>
   
  
    </div>


    <hr />
    <form asp-action="Edit">
                <div class="EditCardGrid">

            
                    <div>

           
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="TaskId" class="control-label" hidden></label>
                            <input asp-for="TaskId" class="form-control" hidden />
                            <input asp-for="ProjectId" class="form-control" hidden />
                        
                            <span asp-validation-for="TaskId" class="text-danger" hidden></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Name"  class="control-label"></label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description" class="control-label"></label>
                            <textarea  asp-for="Description" style="height:300px; width:100%" name="Description" class="form-control"></textarea>
                       
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                     </div>

                    <div style="display:flex; flex-direction:column; gap:18px;">
                        <div class="form-group">
                           <label asp-for="CurTaskStatusId" class="control-label"></label>
                           <select class="form-control" asp-for="CurTaskStatusId" asp-items=@Model.GetTaskList()></select>
                        </div>
                        <div class="form-group">
                            <label asp-for="Start" class="control-label"></label>
                            <input asp-for="Start" class="form-control" />
                            <span asp-validation-for="Start" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="End" class="control-label"></label>
                            <input asp-for="End" class="form-control" />
                        
                            <span asp-validation-for="End" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                             <label>Создал</label>
                        
                            <label  class="form-control" >@Model.GetOwnerName()</label>
                        </div>
                       

                        
               
                    
                    </div>
                </div>
                <br />
                <div class="form-group">

                    <input type="submit" value="Сохранить" class="Dbtn" style="width:100%" />
                </div>
    </form>
       
   
    <hr />
    <div>
         <div style="display:flex">
                             
                            <a class="Dbtn" href="~/TaskTags/Add?TaskId=@Model.TaskId">Добавить теги</a>
                             
                            
                            @foreach(TagTaskInstanceModel m in @Model.Tags)
                            {
                                <div class="DBorder">
                                    <a>@m.Name</a>
                                    <a href="~/TaskTags/RemoveTag?tagInstanceId=@m.Id">X</a>
                                </div>

                                
                            }
          </div>
    </div>



    <div style="display:grid;"  class="blockPadding"  >
         <h3>Файлы</h3>
            <hr />
      
           <div  style="display:flex; flex-wrap:wrap; padding-top:10px">
       
            @foreach(Worky.Models.Project.TaskFile ts in @Model.Task.TaskFiles)
            {
                <div class="DBorder" style="display:grid; grid-template-rows:1fr 1fr;" id="TaskFile-@ts.Id">
                     <a>@ts.Name</a>
                     <div style="display:flex">
                    <form method="post" asp-action ="DownloadTaskFile" asp-controller="Files">
                   
                        <input name="TaskFileId" value="@ts.Id" hidden >
                        <input type="submit" value="Скачать" class="Dbtn">
                    </form>
                    <button onclick="RemoveFile('@ts.Id')" class="Dbtn"> Удалить</button>
                      </div>
         
                </div>
            }
            </div>
            <br />
           <a href="~/Files/AddTaskFile?TaskId=@Model.TaskId" class="Dbtn" style="width:100%; padding-top:10px">Добавить файл</a>
    </div>





    <div class="blockPadding"  >
        <h3>Комментарии</h3>
        <hr />
        <div style="overflow:auto;max-height:300px" >

        @Html.Partial("CommentsView",@Model.CommentModels)
        @*@foreach(Worky.Models.Project.CommentModel c in  @Model.CommentModels)
        {
        
            <div class="list-group-item list-group-item-action py-3 lh-tight"  style="display:flex; flex-direction:column">
                <h5>@c.GetuserName()</h5>
                @c.Comment
                <br>
                <hr>
                <a>@c.DateTime</a>
            </div>
        }*@
        </div>
        <div  style="margin-top:10px">
             @Html.Partial("CommentAddView",new CommentAddModel(){TaskId=Model.TaskId})
        </div>
        
    </div>
</div>